import './globals.css';
import '@/styles/bootstrap.min.css';
import { Inter } from 'next/font/google';

import Provider from '@/components/SessionProvider';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Eber - Skeleton',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Provider>
                    { children }    
                    <Footer />
                </Provider>
            </body>
        </html>
    )
}
